### ISSUE TITLE
Installation documentation

### ISSUE THREAD

**Issue by kearnsw** [gabrielStanovsky/supervised-oie#3]
Hi @gabrielStanovsky,

I just installed this software package and found a couple instructions that need to be updated.

1) pip install **-r** requirements.txt
3) hyperparam directory is missing a **p** in the command line example
3) The training, dev, and test files should have a oie in the middle, e.g. train.conll should be train.oie.conll

Users will also need to install a tagger using NLTK: 
`nltk.download("averaged_perceptron_tagger")`

Thanks for releasing this!

**Comment by kearnsw** [comment]
Also, the training files all have a oie in the middle, e.g. train.conll should be train.oie.conll.

**Comment by gabrielStanovsky** [comment]
Hi @kearnsw, thank you very much for the comments.
I actually just moved the maintenance of this project to the [AllenNLP framework](https://allennlp.org/models#open-information-extraction).
Please see a note about it at the main README file.
The training and prediction there are much simpler.
