### ISSUE TITLE
How can I use the train.noisy.oie.conll file?

### ISSUE THREAD

**Issue by piekey1994** [gabrielStanovsky/supervised-oie#4]
I only use train.oie.conll to train the model. I don't know if I need to use the train.noisy.oie.conll file.
Thanks.

**Comment by gabrielStanovsky** [comment]
Hi @piekey1994, the maintenance of this project has moved to the [AllenNLP framework](https://allennlp.org/models#open-information-extraction). 
Please see a note about it at the main README file.
The training and prediction there are much simpler.
