### ISSUE TITLE
evaluation script

### ISSUE THREAD

**Issue by mingtan888** [gabrielStanovsky/supervised-oie#8]
Hi, 

From your NAACL paper, 
```
To that end, we follow He et al. (2015) which judge an argument
as correct if and only if it includes the syntactic head of the gold argument (and similarly for
predicates).For OIE2016, we use the available Penn Treebank gold syntactic trees (Marcus et al., 1993),
 while for the other test sets, we use predicted trees instead. 
```

I wonder if you have the matching evaluation script with the tree as the input in this repo?
Seems in supervised-oie-benchmark/matcher.py
Matcher.argMatch 
Matcher.predMatch
Matcher.argMatch
Matcher.lexicalMatch

None of them correspond to that?

Thanks!

**Comment by gabrielStanovsky** [comment]
Hi @mingtan888, 
I started with the syntactic head metric to get the results reported in the paper. Later on, I simplified the evaluation metric to the one that's currently in the repo, as it didn't rely on a specific syntactic parser and provided similar results. Specifically, the ranking of the different systems with the new metric remained the same. This is reported in [the changelog in the benchmarking repo](https://github.com/gabrielStanovsky/oie-benchmark#changelog).
